[[server]]
= GRPC Server

* requirements
    ** provide >=1 beans / type `BindableService`
* `Server`
    ** == gRPC server
        *** listens for incoming requests
        *** routes the incoming requests -- to the -- appropriate service implementation

== Create a `BindableService`

* _Example:_ reflection service | `grpc-services` artifact / allows clients can
    ** browse your services' metadata
    ** download the Protobuf files
* create your own `BindableService`
    ** check xref:ROOT:../../../../../../../README.md[here]

== Netty Server

* TODO:
If you use the `spring-grpc-spring-boot-starter` dependency on its own, the `Server` is a Netty-based implementation.
You can configure common features of the server by using the `grpc.server` prefix in `application.properties` or `application.yml`.
For instance, to set the port to listen on, use `spring.grpc.server.port` (defaults to 9090).
For more specialized configuration, you can provide a `ServerBuilderCustomizer` bean to customize the `ServerBuilder` before it is used to create the server.

=== Shaded Netty

You can switch to a shaded Netty provided by the gRPC team by adding the `grpc-netty-shaded` dependency and excluding the `grpc-netty` dependency.

[source,xml]
----
<dependency>
	<groupId>org.springframework.grpc</groupId>
	<artifactId>spring-grpc-spring-boot-starter</artifactId>
	<exclusions>
		<exclusion>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-netty</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>io.grpc</groupId>
	<artifactId>grpc-netty-shaded</artifactId>
</dependency>
----

For Gradle users

[source,gradle]
----
dependencies {
	implementation "org.springframework.grpc:spring-grpc-spring-boot-starter"
	implementation 'io.grpc:grpc-netty-shaded'
	modules {
		module("io.grpc:grpc-netty") {
			replacedBy("io.grpc:grpc-netty-shaded", "Use Netty shaded instead of regular Netty")
		}
	}
}
----

== Servlet Server

* servlet container
    ** -- can be used to -- run a gRPC server
        *** HTTP POST requests -- are mapped to the -- paths / defined by the registered services (_Example:_ `/<service-name>/*`)
* requirements
    ** include `spring-boot-starter-web` | your application

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.grpc</groupId>
	<artifactId>spring-grpc-spring-boot-starter</artifactId>
</dependency>
----


[source,gradle]
----
dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.grpc:spring-grpc-spring-boot-starter"
}
----

* `spring.grpc.server.*` properties
    ** 👀-- ignored in favour of the -- regular `server.*` 👀
